# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.probe_update import ProbeUpdate

class TestProbeUpdate(unittest.TestCase):
    """ProbeUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProbeUpdate:
        """Test ProbeUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProbeUpdate`
        """
        model = ProbeUpdate()
        if include_optional:
            return ProbeUpdate(
                data_column_index = 56,
                name = '',
                position_x = '',
                position_y = '',
                tray_id = ''
            )
        else:
            return ProbeUpdate(
        )
        """

    def testProbeUpdate(self):
        """Test ProbeUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
