# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_one_asset(self) -> None:
        """Test case for create_one_asset

        Create one asset
        """
        pass

    def test_create_one_experiment(self) -> None:
        """Test case for create_one_experiment

        Create one experiment
        """
        pass

    def test_create_one_location(self) -> None:
        """Test case for create_one_location

        Create one location
        """
        pass

    def test_create_one_project(self) -> None:
        """Test case for create_one_project

        Create one project
        """
        pass

    def test_create_one_sample(self) -> None:
        """Test case for create_one_sample

        Create one sample
        """
        pass

    def test_create_one_tray_configuration(self) -> None:
        """Test case for create_one_tray_configuration

        Create one tray_configuration
        """
        pass

    def test_create_one_treatment(self) -> None:
        """Test case for create_one_treatment

        Create one treatment
        """
        pass

    def test_delete_many_assets(self) -> None:
        """Test case for delete_many_assets

        Delete many assets
        """
        pass

    def test_delete_many_experiments(self) -> None:
        """Test case for delete_many_experiments

        Delete many experiments
        """
        pass

    def test_delete_many_locations(self) -> None:
        """Test case for delete_many_locations

        Delete many locations
        """
        pass

    def test_delete_many_projects(self) -> None:
        """Test case for delete_many_projects

        Delete many projects
        """
        pass

    def test_delete_many_samples(self) -> None:
        """Test case for delete_many_samples

        Delete many samples
        """
        pass

    def test_delete_many_tray_configurations(self) -> None:
        """Test case for delete_many_tray_configurations

        Delete many tray_configurations
        """
        pass

    def test_delete_many_treatments(self) -> None:
        """Test case for delete_many_treatments

        Delete many treatments
        """
        pass

    def test_delete_one_asset(self) -> None:
        """Test case for delete_one_asset

        Delete one asset
        """
        pass

    def test_delete_one_experiment(self) -> None:
        """Test case for delete_one_experiment

        Delete one experiment
        """
        pass

    def test_delete_one_location(self) -> None:
        """Test case for delete_one_location

        Delete one location
        """
        pass

    def test_delete_one_project(self) -> None:
        """Test case for delete_one_project

        Delete one project
        """
        pass

    def test_delete_one_sample(self) -> None:
        """Test case for delete_one_sample

        Delete one sample
        """
        pass

    def test_delete_one_tray_configuration(self) -> None:
        """Test case for delete_one_tray_configuration

        Delete one tray_configuration
        """
        pass

    def test_delete_one_treatment(self) -> None:
        """Test case for delete_one_treatment

        Delete one treatment
        """
        pass

    def test_get_all_assets(self) -> None:
        """Test case for get_all_assets

        Get all assets
        """
        pass

    def test_get_all_experiments(self) -> None:
        """Test case for get_all_experiments

        Get all experiments
        """
        pass

    def test_get_all_locations(self) -> None:
        """Test case for get_all_locations

        Get all locations
        """
        pass

    def test_get_all_projects(self) -> None:
        """Test case for get_all_projects

        Get all projects
        """
        pass

    def test_get_all_samples(self) -> None:
        """Test case for get_all_samples

        Get all samples
        """
        pass

    def test_get_all_tray_configurations(self) -> None:
        """Test case for get_all_tray_configurations

        Get all tray_configurations
        """
        pass

    def test_get_all_treatments(self) -> None:
        """Test case for get_all_treatments

        Get all treatments
        """
        pass

    def test_get_one_asset(self) -> None:
        """Test case for get_one_asset

        Get one asset
        """
        pass

    def test_get_one_experiment(self) -> None:
        """Test case for get_one_experiment

        Get one experiment
        """
        pass

    def test_get_one_location(self) -> None:
        """Test case for get_one_location

        Get one location
        """
        pass

    def test_get_one_project(self) -> None:
        """Test case for get_one_project

        Get one project
        """
        pass

    def test_get_one_sample(self) -> None:
        """Test case for get_one_sample

        Get one sample
        """
        pass

    def test_get_one_tray_configuration(self) -> None:
        """Test case for get_one_tray_configuration

        Get one tray_configuration
        """
        pass

    def test_get_one_treatment(self) -> None:
        """Test case for get_one_treatment

        Get one treatment
        """
        pass

    def test_get_ui_config(self) -> None:
        """Test case for get_ui_config

        """
        pass

    def test_healthz(self) -> None:
        """Test case for healthz

        """
        pass

    def test_update_one_asset(self) -> None:
        """Test case for update_one_asset

        Update one asset
        """
        pass

    def test_update_one_experiment(self) -> None:
        """Test case for update_one_experiment

        Update one experiment
        """
        pass

    def test_update_one_location(self) -> None:
        """Test case for update_one_location

        Update one location
        """
        pass

    def test_update_one_project(self) -> None:
        """Test case for update_one_project

        Update one project
        """
        pass

    def test_update_one_sample(self) -> None:
        """Test case for update_one_sample

        Update one sample
        """
        pass

    def test_update_one_tray_configuration(self) -> None:
        """Test case for update_one_tray_configuration

        Update one tray_configuration
        """
        pass

    def test_update_one_treatment(self) -> None:
        """Test case for update_one_treatment

        Update one treatment
        """
        pass


if __name__ == '__main__':
    unittest.main()
