# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.location_update import LocationUpdate

class TestLocationUpdate(unittest.TestCase):
    """LocationUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LocationUpdate:
        """Test LocationUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LocationUpdate`
        """
        model = LocationUpdate()
        if include_optional:
            return LocationUpdate(
                comment = '',
                name = '',
                project_id = ''
            )
        else:
            return LocationUpdate(
        )
        """

    def testLocationUpdate(self):
        """Test LocationUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
