# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.tray_configuration_list import TrayConfigurationList

class TestTrayConfigurationList(unittest.TestCase):
    """TrayConfigurationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrayConfigurationList:
        """Test TrayConfigurationList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrayConfigurationList`
        """
        model = TrayConfigurationList()
        if include_optional:
            return TrayConfigurationList(
                experiment_default = True,
                id = '',
                name = '',
                trays = [
                    spice_client.models.tray_list.TrayList(
                        id = '', 
                        lower_right_corner_x = 56, 
                        lower_right_corner_y = 56, 
                        name = '', 
                        order_sequence = 56, 
                        probe_locations = [
                            spice_client.models.probe_list.ProbeList(
                                data_column_index = 56, 
                                id = '', 
                                name = '', 
                                position_x = '', 
                                position_y = '', )
                            ], 
                        qty_cols = 56, 
                        qty_rows = 56, 
                        rotation_degrees = 56, 
                        upper_left_corner_x = 56, 
                        upper_left_corner_y = 56, 
                        well_relative_diameter = '', )
                    ]
            )
        else:
            return TrayConfigurationList(
                experiment_default = True,
                id = '',
                trays = [
                    spice_client.models.tray_list.TrayList(
                        id = '', 
                        lower_right_corner_x = 56, 
                        lower_right_corner_y = 56, 
                        name = '', 
                        order_sequence = 56, 
                        probe_locations = [
                            spice_client.models.probe_list.ProbeList(
                                data_column_index = 56, 
                                id = '', 
                                name = '', 
                                position_x = '', 
                                position_y = '', )
                            ], 
                        qty_cols = 56, 
                        qty_rows = 56, 
                        rotation_degrees = 56, 
                        upper_left_corner_x = 56, 
                        upper_left_corner_y = 56, 
                        well_relative_diameter = '', )
                    ],
        )
        """

    def testTrayConfigurationList(self):
        """Test TrayConfigurationList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
