# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.tray_well_summary import TrayWellSummary

class TestTrayWellSummary(unittest.TestCase):
    """TrayWellSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrayWellSummary:
        """Test TrayWellSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrayWellSummary`
        """
        model = TrayWellSummary()
        if include_optional:
            return TrayWellSummary(
                column_number = 56,
                coordinate = '',
                dilution_factor = 56,
                first_phase_change_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                image_asset_id = '',
                row_letter = '',
                sample = spice_client.models.sample.Sample(
                    air_volume_litres = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    extraction_procedure = '', 
                    filter_substrate = '', 
                    flow_litres_per_minute = '', 
                    id = '', 
                    initial_concentration_gram_l = '', 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    latitude = '', 
                    location = spice_client.models.location.Location(
                        area = null, 
                        color = '', 
                        comment = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        name = '', 
                        project_id = '', 
                        project_name = '', ), 
                    location_id = '', 
                    longitude = '', 
                    material_description = '', 
                    name = '', 
                    remarks = '', 
                    start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    stop_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    suspension_volume_litres = '', 
                    total_volume = '', 
                    treatments = [
                        spice_client.models.treatment.Treatment(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            dilution_summaries = [
                                spice_client.models.dilution_summary.DilutionSummary(
                                    dilution_factor = 56, 
                                    statistics = spice_client.models.nucleation_statistics.NucleationStatistics(
                                        frozen_count = 0, 
                                        liquid_count = 0, 
                                        mean_nucleation_temp_celsius = 1.337, 
                                        median_nucleation_time_seconds = 56, 
                                        success_rate = 1.337, 
                                        total_wells = 0, ), )
                                ], 
                            enzyme_volume_litres = '', 
                            experimental_results = [
                                spice_client.models.nucleation_event.NucleationEvent(
                                    dilution_factor = 56, 
                                    experiment_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    experiment_id = '', 
                                    experiment_name = '', 
                                    final_state = '', 
                                    freezing_temperature_avg = '', 
                                    freezing_time_seconds = 56, 
                                    nucleation_temperature_avg_celsius = '', 
                                    nucleation_time_seconds = 56, 
                                    tray_name = '', 
                                    treatment_id = '', 
                                    treatment_name = '', 
                                    well_coordinate = '', )
                                ], 
                            id = '', 
                            last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            name = 'none', 
                            notes = '', 
                            sample_id = '', 
                            statistics = spice_client.models.nucleation_statistics.NucleationStatistics(
                                frozen_count = 0, 
                                liquid_count = 0, 
                                mean_nucleation_temp_celsius = 1.337, 
                                median_nucleation_time_seconds = 56, 
                                success_rate = 1.337, 
                                total_wells = 0, ), )
                        ], 
                    type = 'bulk', 
                    water_volume_litres = '', 
                    well_volume_litres = '', ),
                temperatures = spice_client.models.temperature_data_with_probes.TemperatureDataWithProbes(
                    average = '', 
                    experiment_id = '', 
                    id = '', 
                    image_filename = '', 
                    probe_readings = [
                        spice_client.models.probe_temperature_reading_with_metadata.ProbeTemperatureReadingWithMetadata(
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            id = '', 
                            probe_data_column_index = 56, 
                            probe_id = '', 
                            probe_name = '', 
                            probe_position_x = '', 
                            probe_position_y = '', 
                            temperature = '', 
                            temperature_reading_id = '', )
                        ], 
                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                total_phase_changes = 0,
                treatment = spice_client.models.treatment.Treatment(
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    dilution_summaries = [
                        spice_client.models.dilution_summary.DilutionSummary(
                            dilution_factor = 56, 
                            statistics = spice_client.models.nucleation_statistics.NucleationStatistics(
                                frozen_count = 0, 
                                liquid_count = 0, 
                                mean_nucleation_temp_celsius = 1.337, 
                                median_nucleation_time_seconds = 56, 
                                success_rate = 1.337, 
                                total_wells = 0, ), )
                        ], 
                    enzyme_volume_litres = '', 
                    experimental_results = [
                        spice_client.models.nucleation_event.NucleationEvent(
                            dilution_factor = 56, 
                            experiment_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            experiment_id = '', 
                            experiment_name = '', 
                            final_state = '', 
                            freezing_temperature_avg = '', 
                            freezing_time_seconds = 56, 
                            nucleation_temperature_avg_celsius = '', 
                            nucleation_time_seconds = 56, 
                            tray_name = '', 
                            treatment_id = '', 
                            treatment_name = '', 
                            well_coordinate = '', )
                        ], 
                    id = '', 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = 'none', 
                    notes = '', 
                    sample_id = '', 
                    statistics = spice_client.models.nucleation_statistics.NucleationStatistics(
                        frozen_count = 0, 
                        liquid_count = 0, 
                        mean_nucleation_temp_celsius = 1.337, 
                        median_nucleation_time_seconds = 56, 
                        success_rate = 1.337, 
                        total_wells = 0, ), )
            )
        else:
            return TrayWellSummary(
                column_number = 56,
                coordinate = '',
                row_letter = '',
                total_phase_changes = 0,
        )
        """

    def testTrayWellSummary(self):
        """Test TrayWellSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
