# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.treatment_name import TreatmentName

class TestTreatmentName(unittest.TestCase):
    """TreatmentName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTreatmentName(self):
        """Test TreatmentName"""
        # inst = TreatmentName()

if __name__ == '__main__':
    unittest.main()
