# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.temperature_data_with_probes import TemperatureDataWithProbes

class TestTemperatureDataWithProbes(unittest.TestCase):
    """TemperatureDataWithProbes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemperatureDataWithProbes:
        """Test TemperatureDataWithProbes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemperatureDataWithProbes`
        """
        model = TemperatureDataWithProbes()
        if include_optional:
            return TemperatureDataWithProbes(
                average = '',
                experiment_id = '',
                id = '',
                image_filename = '',
                probe_readings = [
                    spice_client.models.probe_temperature_reading_with_metadata.ProbeTemperatureReadingWithMetadata(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        probe_data_column_index = 56, 
                        probe_id = '', 
                        probe_name = '', 
                        probe_position_x = '', 
                        probe_position_y = '', 
                        temperature = '', 
                        temperature_reading_id = '', )
                    ],
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TemperatureDataWithProbes(
                experiment_id = '',
                id = '',
                probe_readings = [
                    spice_client.models.probe_temperature_reading_with_metadata.ProbeTemperatureReadingWithMetadata(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        probe_data_column_index = 56, 
                        probe_id = '', 
                        probe_name = '', 
                        probe_position_x = '', 
                        probe_position_y = '', 
                        temperature = '', 
                        temperature_reading_id = '', )
                    ],
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTemperatureDataWithProbes(self):
        """Test TemperatureDataWithProbes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
