# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.sample_create import SampleCreate

class TestSampleCreate(unittest.TestCase):
    """SampleCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SampleCreate:
        """Test SampleCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SampleCreate`
        """
        model = SampleCreate()
        if include_optional:
            return SampleCreate(
                air_volume_litres = '',
                extraction_procedure = '',
                filter_substrate = '',
                flow_litres_per_minute = '',
                initial_concentration_gram_l = '',
                latitude = '',
                location = spice_client.models.location.Location(
                    area = null, 
                    color = '', 
                    comment = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    id = '', 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    name = '', 
                    project_id = '', 
                    project_name = '', ),
                location_id = '',
                longitude = '',
                material_description = '',
                name = '',
                remarks = '',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                stop_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                suspension_volume_litres = '',
                total_volume = '',
                treatments = [
                    spice_client.models.treatment_create.TreatmentCreate(
                        enzyme_volume_litres = '', 
                        name = 'none', 
                        notes = '', 
                        sample_id = '', )
                    ],
                type = 'bulk',
                water_volume_litres = '',
                well_volume_litres = ''
            )
        else:
            return SampleCreate(
                name = '',
                type = 'bulk',
        )
        """

    def testSampleCreate(self):
        """Test SampleCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
