# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.sample_type import SampleType

class TestSampleType(unittest.TestCase):
    """SampleType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSampleType(self):
        """Test SampleType"""
        # inst = SampleType()

if __name__ == '__main__':
    unittest.main()
