# coding: utf-8

"""
    spice-api

    API for managing SPICE lab data in the EERL lab

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spice_client.models.asset_create import AssetCreate

class TestAssetCreate(unittest.TestCase):
    """AssetCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetCreate:
        """Test AssetCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetCreate`
        """
        model = AssetCreate()
        if include_optional:
            return AssetCreate(
                experiment_id = '',
                is_deleted = True,
                original_filename = '',
                processing_message = '',
                processing_status = '',
                role = '',
                s3_key = '',
                size_bytes = 56,
                type = '',
                uploaded_by = ''
            )
        else:
            return AssetCreate(
                is_deleted = True,
                original_filename = '',
                s3_key = '',
                type = '',
        )
        """

    def testAssetCreate(self):
        """Test AssetCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
